version: '3'

services:
  ansible:
    image: willhallonline/ansible:latest
    container_name: ansible
    network_mode: host
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./reports:/ansible/reports
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    restart: unless-stopped
